CREATE TABLE CATEGORIA
(
   ID BIGINT PRIMARY KEY AUTO_INCREMENT,
   DESCRICAO varchar(255) not null
);



CREATE TABLE PRODUTO
(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
   DESCRICAO varchar(255) not null,
   ATIVO BOOLEAN,
   primary key(id)
);