CREATE TABLE CATEGORIA
(
   ID BIGINT PRIMARY KEY AUTO_INCREMENT,
   DESCRICAO varchar(255) not null,
    ATIVO BOOLEAN,
    primary key(id)
);



CREATE TABLE PRODUTO
(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
   DESCRICAO varchar(255) not null,
   ATIVO BOOLEAN,
   ID_CATEGORIA INT, 
   primary key(ID),
    FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);